//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Speedtest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Speedtest.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Global_Error {
            get {
                return ResourceManager.GetString("Global_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No port selected!.
        /// </summary>
        internal static string Global_Error_NoPortSelected {
            get {
                return ResourceManager.GetString("Global_Error_NoPortSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Global_Start {
            get {
                return ResourceManager.GetString("Global_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Global_Stop {
            get {
                return ResourceManager.GetString("Global_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        internal static string Import_DisplayMode_FFT {
            get {
                return ResourceManager.GetString("Import_DisplayMode_FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        internal static string Import_DisplayMode_Histogram {
            get {
                return ResourceManager.GetString("Import_DisplayMode_Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrollable.
        /// </summary>
        internal static string Import_DisplayMode_Scroll {
            get {
                return ResourceManager.GetString("Import_DisplayMode_Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files (*.csv)|*.csv.
        /// </summary>
        internal static string Import_FileFilter_CSV {
            get {
                return ResourceManager.GetString("Import_FileFilter_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt.
        /// </summary>
        internal static string Import_FileFilter_TXT {
            get {
                return ResourceManager.GetString("Import_FileFilter_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs importált fájl!.
        /// </summary>
        internal static string Import_NoFilesImported {
            get {
                return ResourceManager.GetString("Import_NoFilesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Import_ShowButtonCaption {
            get {
                return ResourceManager.GetString("Import_ShowButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string MeasureTab_DisplayMode_Chart {
            get {
                return ResourceManager.GetString("MeasureTab_DisplayMode_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        internal static string MeasureTab_DisplayMode_Monitor {
            get {
                return ResourceManager.GetString("MeasureTab_DisplayMode_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY .
        /// </summary>
        internal static string MeasureTab_DisplayMode_XY {
            get {
                return ResourceManager.GetString("MeasureTab_DisplayMode_XY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number panels are greater than the incoming datas..
        /// </summary>
        internal static string PortController_GreaterIncomingDataError {
            get {
                return ResourceManager.GetString("PortController_GreaterIncomingDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .csv.
        /// </summary>
        internal static string Recording_ExportinFileFormat_CSV {
            get {
                return ResourceManager.GetString("Recording_ExportinFileFormat_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string Recording_ExportinFileFormat_TXT {
            get {
                return ResourceManager.GetString("Recording_ExportinFileFormat_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Destination.
        /// </summary>
        internal static string Recording_FileDestinationButton {
            get {
                return ResourceManager.GetString("Recording_FileDestinationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Recording.
        /// </summary>
        internal static string Recording_Start {
            get {
                return ResourceManager.GetString("Recording_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop  Recording.
        /// </summary>
        internal static string Recording_Stop {
            get {
                return ResourceManager.GetString("Recording_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channels found.
        /// </summary>
        internal static string Statistic_ChannelsFound {
            get {
                return ResourceManager.GetString("Statistic_ChannelsFound", resourceCulture);
            }
        }
    }
}
